disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Layer Zero"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"
description = "Musings of a computer nerd."

["params.author"]
name = "Sumedh Girish"
